name: Build

on:
  pull_request:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'

      - name: Install buf
        run: |
            wget -O buf "https://github.com/bufbuild/buf/releases/download/v1.16.0/buf-$(uname -s)-$(uname -m)"
            chmod +x buf
            sudo mv buf /usr/local/bin
            buf --version

      - name: Install dependencies
        run: npm install

      - name: Generate code (.proto -> .ts)
        run: npm run codegen

      - name: Ensure schemas are up-to-date
        run: |
            CHANGES_IN_REPO=$(git status --porcelain)
            if [[ -n "$CHANGES_IN_REPO" ]]; then
              echo "Repository is dirty. Showing 'git status' and 'git --no-pager diff' for debugging now:"
              git status && git --no-pager diff
              exit 1
            fi

      - name: Build (.ts -> .js/.d.ts)
        run: npm run build
